---
branches:
  - stable
projects:
  MultiWorld:
    path: ''
    icon: icon.png
    libs:
      Commando:
        src: Swim-Services/Commando-MV/Commando
        version: ^3.2.0
      PMForms:
        src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
      VanillaGenerator:
        src: CzechPMDevs/VanillaGenerator/VanillaGenerator
        version: ^0.0.6
    lint:
      phpstan: false
...
